runtime: python38
env: standard
instance_class: F4_HIGHMEM

entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /
  script: auto

- url: /static
  static_dir: ../static

- url: /images
  static_dir: ../static/images

- url: /fav
  static_dir: ../static/images/fav
