runtime: python38

instance_class: F4_1G

# entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /
  script: auto

- url: /static
  static_dir: static

- url: /images
  static_dir: ../static/images

- url: /fav
  static_dir: ../static/images/fav
